# Generated by Django 5.1.7 on 2025-11-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdf_documents', '0002_matchedtext_pdfpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_type', models.CharField(max_length=50)),
                ('figure_box', models.JSONField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_documents.pdfpage')),
            ],
        ),
    ]
