# Generated by Django 5.1.7 on 2025-11-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdf_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('tag_detail', models.CharField(max_length=100)),
                ('pdf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_documents.originpdf')),
            ],
        ),
    ]
