# Generated by Django 5.1.7 on 2025-11-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.TextField()),
                ('highlight_box', models.JSONField()),
                ('Tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highlights.tag')),
            ],
        ),
    ]
