# Generated by Django 5.1.7 on 2025-11-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_highlight'),
        ('pdf_documents', '0002_matchedtext_pdfpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_documents.pdfpage'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='pdf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_documents.originpdf'),
        ),
    ]
