# Generated by Django 5.1.7 on 2025-11-04 09:25

import accounts.models
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='username은 3~30자의 영문/숫자/언더스코어만 허용됩니다.', regex='^[a-zA-Z0-9_]{3,30}$')])),
                ('field', models.CharField(blank=True, db_column='Field', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('username'), condition=models.Q(('username__isnull', False)), name='uniq_username_ci_notnull')],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
