# Generated by Django 5.1.7 on 2025-11-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('raw_text', models.TextField()),
                ('matched_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PDFpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
