# Generated by Django 5.1.7 on 2025-11-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_documents', '0002_matchedtext_pdfpage'),
        ('pdf_figures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedtext',
            name='figure_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_figures.pdffigure'),
        ),
        migrations.AddField(
            model_name='pdfpage',
            name='pdf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_documents.originpdf'),
        ),
        migrations.AddField(
            model_name='matchedtext',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_documents.pdfpage'),
        ),
    ]
