# Generated by Django 5.1.7 on 2025-11-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_documents', '0003_matchedtext_figure_id_pdfpage_pdf_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originpdf',
            name='s3_key',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='originpdf',
            name='S3_url',
            field=models.URLField(),
        ),
    ]
