# Generated by Django 5.1.7 on 2025-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_documents', '0004_originpdf_s3_key_alter_originpdf_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedtext',
            name='text_box',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
